// Mocks generated by Mockito 5.4.3 from annotations
// in hr_app_flutter/test/user_birthday_test/user_birthday_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:hr_app_flutter/features/services/model/birth_day_info/birth_day_info.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$BirthDayInfoEntityCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$BirthDayInfoEntityCopyWith<$Res> {
  _Fake$BirthDayInfoEntityCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BirthDayInfoEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockBirthDayInfoEntity extends _i1.Mock
    implements _i2.BirthDayInfoEntity {
  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  List<_i2.OneBirthDayInfo> get birthdays => (super.noSuchMethod(
        Invocation.getter(#birthdays),
        returnValue: <_i2.OneBirthDayInfo>[],
        returnValueForMissingStub: <_i2.OneBirthDayInfo>[],
      ) as List<_i2.OneBirthDayInfo>);
  @override
  _i2.$BirthDayInfoEntityCopyWith<_i2.BirthDayInfoEntity> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$BirthDayInfoEntityCopyWith_0<_i2.BirthDayInfoEntity>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub:
            _Fake$BirthDayInfoEntityCopyWith_0<_i2.BirthDayInfoEntity>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$BirthDayInfoEntityCopyWith<_i2.BirthDayInfoEntity>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
