// Mocks generated by Mockito 5.4.3 from annotations
// in hr_app_flutter/test/rookies_test/rookies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:hr_app_flutter/features/services/bloc/rookies_bloc/rookies_bloc.dart'
    as _i3;
import 'package:hr_app_flutter/features/services/model/rookies_entity/rookies.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$RookiesCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$RookiesCopyWith<$Res> {
  _Fake$RookiesCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RookiesEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockRookiesEntity extends _i1.Mock implements _i3.RookiesEntity {
  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  List<_i2.OneRookiesInfo> get rookies => (super.noSuchMethod(
        Invocation.getter(#rookies),
        returnValue: <_i2.OneRookiesInfo>[],
        returnValueForMissingStub: <_i2.OneRookiesInfo>[],
      ) as List<_i2.OneRookiesInfo>);
  @override
  _i2.$RookiesCopyWith<_i2.Rookies> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$RookiesCopyWith_0<_i2.Rookies>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$RookiesCopyWith_0<_i2.Rookies>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$RookiesCopyWith<_i2.Rookies>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
